feat: redirector
edgehog-device-manager/edgehog_device_forwarder pull request #11
Opened 2023-10-03 17:03 UTC by noaccOS

Module to handle protobuf encoding/decoding and middleman between sockets/controllers

depends on #8 and includes its commits

2023-10-16 16:00 UTC, noaccOS commented
Module moved to `edgehog_device_forwarder/forwarder.ex` and added some tests

2023-11-23 16:21 UTC, Annopaolo requested changes

2023-11-23 16:21 UTC, Annopaolo commented on mix.exs
> +        sparse: "elixir/edgehog_device_forwarder_proto"
![gif](https://media.giphy.com/media/dgK22exekwOLm/giphy.gif)

2023-11-23 16:37 UTC, noaccOS commented on mix.exs
> +        sparse: "elixir/edgehog_device_forwarder_proto"
Hasn't been merged yet ¯\\\_(ツ)_/¯

2023-12-20 17:31 UTC, noaccOS commented on mix.exs
> +        sparse: "elixir/edgehog_device_forwarder_proto"
it has since been merged and the dependency has been updated to point to upstream.

2023-12-21 09:53 UTC, rbino approved these changes

2023-12-21 09:54 UTC, merged